# Generated by Django 4.2.1 on 2023-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=1, upload_to="fruit_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="prediction",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
